#!/usr/bin/env bash
# FIZZBUZZ

for nm in {1..100}
do
if (( nm % 5 == 0 && nm % 3 ==0 ))
then
echo "FizzBuzz"
elif ((nm % 3 == 0))
then
echo "Fizz"
elif ((nm % 5 == 0))
then
echo "Buzz"
else
echo "$nm"
fi
done

