#!/usr/bin/env bash
# Displys "bad luck on the 4th 'good luck' on the 8th and 'Best School' else usg a 'for' loop

count=1

while [ $count -le 10 ]
do
    if [ $count -eq 4 ]; then
        echo "bad luck"
    elif [ $count -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi

    count=$((count + 1))
done

